[package]
name = "dbmd-backend-clickhouse"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[features]
clickhouse-tests = ["dep:dbmd-test-support", "dbmd-test-support/clickhouse"]

[dependencies]
dbmd-core = { path = "../../core" }
dbmd-relational = { path = "../relational" }
dbmd-render = { path = "../../render" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
dbmd-test-support = { path = "../../test-support", optional = true }
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true

[[test]]
name = "clickhouse"
required-features = ["clickhouse-tests"]
