[package]
name = "dbmd-backend-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[features]
postgres-tests = ["dep:dbmd-test-support"]

[dependencies]
dbmd-core = { path = "../../core" }
dbmd-relational = { path = "../relational" }
dbmd-render = { path = "../../render" }
dbmd-test-support = { path = "../../test-support", optional = true }
postgres.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true

[[test]]
name = "postgres"
required-features = ["postgres-tests"]
