CREATE SCHEMA empty_space;
COMMENT ON SCHEMA empty_space IS 'Reserved for future objects';

CREATE SCHEMA catalog;

CREATE TYPE catalog.account_state AS ENUM ('invited', 'active', 'suspended');
COMMENT ON TYPE catalog.account_state IS 'Lifecycle of an account';

CREATE TABLE catalog.accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    state catalog.account_state NOT NULL DEFAULT 'invited'
);

CREATE VIEW catalog.active_accounts
WITH (security_barrier = true, security_invoker = true) AS
SELECT id, email
FROM catalog.accounts
WHERE state = 'active'
WITH LOCAL CHECK OPTION;

COMMENT ON VIEW catalog.active_accounts IS 'Accounts allowed to sign in';

CREATE MATERIALIZED VIEW catalog.account_counts
USING heap
WITH (fillfactor = 80)
TABLESPACE pg_default AS
SELECT state, count(*) AS account_count
FROM catalog.accounts
GROUP BY state
WITH NO DATA;

CREATE INDEX account_counts_state_idx
ON catalog.account_counts (state);

COMMENT ON INDEX catalog.account_counts_state_idx IS
    'Supports state lookups on the account summary';

CREATE FUNCTION catalog.normalize_email(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURN lower(trim(value));

COMMENT ON FUNCTION catalog.normalize_email(text) IS 'Normalizes an email address';

CREATE PROCEDURE catalog.archive_account(
    IN account_id bigint,
    INOUT archived boolean,
    IN reason text DEFAULT 'manual'
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO catalog, pg_temp
AS $$
BEGIN
    archived := account_id > 0 AND reason <> '';
END;
$$;

COMMENT ON PROCEDURE catalog.archive_account(bigint, boolean, text)
IS 'Marks an account archive request';
