set shell := ["bash", "-euo", "pipefail", "-c"]

default:
    @just --list

render: setup
    MYSQL_URL=mysql://root@127.0.0.1:53306/test dbmd render

verify: setup
    MYSQL_URL=mysql://root@127.0.0.1:53306/test dbmd verify

down:
    docker compose down --volumes --remove-orphans

[private]
setup:
    docker compose down --volumes --remove-orphans
    docker compose up --detach --wait
