CREATE SCHEMA empty_space;
COMMENT ON SCHEMA empty_space IS 'Reserved for future objects';

CREATE SCHEMA catalog;

CREATE TYPE catalog.account_state AS ENUM ('invited', 'active', 'suspended');
COMMENT ON TYPE catalog.account_state IS 'Lifecycle of an account';

CREATE TABLE catalog.accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    state catalog.account_state NOT NULL DEFAULT 'invited'
);

CREATE VIEW catalog.active_accounts AS
SELECT id, email
FROM catalog.accounts
WHERE state = 'active';

COMMENT ON VIEW catalog.active_accounts IS 'Accounts allowed to sign in';

CREATE MATERIALIZED VIEW catalog.account_counts AS
SELECT state, count(*) AS account_count
FROM catalog.accounts
GROUP BY state;

CREATE FUNCTION catalog.normalize_email(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURN lower(trim(value));

COMMENT ON FUNCTION catalog.normalize_email(text) IS 'Normalizes an email address';
